;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programing source file located at
;; https://github.com/gicrisf/emacs-config
;; You should make any changes there and regenerate it from Emacs org-mode
;; using org-babel-tangle (C-c C-v t)

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!


;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "gicrisf"
      user-mail-address "giovanni.crisalfi@protonmail.com")

;; Thanks to
;; https://stackoverflow.com/a/30568768
(defun eval-file (file)
  "Execute FILE and return the result of the last expression."
  (load-file file)
  (with-temp-buffer
    (insert-file-contents file)
    (emacs-lisp-mode)
    (goto-char (point-max))
    (backward-sexp)
    (eval (sexp-at-point))))

;; This file could be placed anywhere
(setq env-vars-file-path "~/.envvars")

(defun load-env-vars ()
  (let ((env-var-list (eval-file env-vars-file-path)))
    (mapc (lambda (cons-cell)
            (setenv (car cons-cell) (car (cdr cons-cell)))) env-var-list)))

(load-env-vars)

(defun bash-load-env-vars ()
  (let* ((env-var-list (eval-file env-vars-file-path))
         (bash-strings (mapcar (lambda (cons-cell)
                                 (concat "export "
                                         (car cons-cell) "="
                                         (concat "'" (car (cdr cons-cell)) "'")))
                               env-var-list)))
    (with-temp-file "~/.bashvars"
      (mapc (lambda (exp_string)
              (insert (concat exp_string "\n"))) bash-strings))))

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
(setq doom-font (font-spec :family "Noto Sans Mono" :size (string-to-number (getenv "DOOM_FONT")) :weight 'semi-light)
      doom-variable-pitch-font (font-spec :family "sans" :size (string-to-number (getenv "DOOM_VARIABLE_PITCH_FONT"))))

(map!
 :n "C-=" #'doom/reset-font-size
 :n "C-+" #'text-scale-increase
 :n "C--" #'text-scale-decrease)

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-city-lights)

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

;; Theme switcher functions
(defvar quick-switch-themes
  (let ((themes-list (list 'lambda-dark
                           'lambda-light)))
    (nconc themes-list themes-list))
  "A circular list of themes to keep switching between.
Make sure that the currently enabled theme is at the head of this
list always.

A nil value implies no custom theme should be enabled.")

;; Thanks to narendraj9, user of emacs.stackexchange.com
;; https://emacs.stackexchange.com/questions/24088/make-a-function-to-toggle-themes
;; I just tweaked his code.
(defun toggle-theme ()
  (interactive)
  (if-let* ((next-theme (cadr quick-switch-themes)))
      (progn (when-let* ((current-theme (car quick-switch-themes)))
               (disable-theme (car quick-switch-themes)))
             (load-theme next-theme t)
             (message "Loaded theme: %s" next-theme))
    ;; Always have the dark mode-line theme
    (mapc #'disable-theme (delq 'smart-mode-line-dark custom-enabled-themes)))
  (setq quick-switch-themes (cdr quick-switch-themes)))

(map! :leader
      :desc "Quick toggle theme" "t t" #'toggle-theme)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/Dropbox/org/")

(require 'org-download)
(add-hook 'dired-mode-hook 'org-download-enable)

;; org journal
;; in ~/.doom.d/+bindings.el
;; From: https://www.rousette.org.uk/archives/doom-emacs-tweaks-org-journal-and-org-super-agenda/
(map! :leader
      (:prefix ("j" . "journal") ;; org-journal bindings
        :desc "Create new journal entry" "j" #'org-journal-new-entry
        :desc "Open previous entry" "p" #'org-journal-open-previous-entry
        :desc "Open next entry" "n" #'org-journal-open-next-entry
        :desc "Search journal" "s" #'org-journal-search-forever))

;; The built-in calendar mode mappings for org-journal
;; conflict with evil bindings
(map!
 (:map calendar-mode-map
   :n "o" #'org-journal-display-entry
   :n "p" #'org-journal-previous-entry
   :n "n" #'org-journal-next-entry
   :n "O" #'org-journal-new-date-entry))

;; Local leader (<SPC m>) bindings for org-journal in calendar-mode
;; I was running out of bindings, and these are used less frequently
;; so it is convenient to have them under the local leader prefix
(map!
 :map (calendar-mode-map)
 :localleader
 "w" #'org-journal-search-calendar-week
 "m" #'org-journal-search-calendar-month
 "y" #'org-journal-search-calendar-year)

(setq org-journal-dir "~/org/amalgam")
(setq org-journal-file-format "%Y-%m.org")
(setq org-journal-file-type 'monthly)

;; org-capture
(setq org-capture-templates `(
	("p" "Protocol" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
        "* %^{Title}\nSource: %u, %c\n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?")
	("L" "Protocol Link" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
        "* %? [[%:link][%:description]] \nCaptured On: %U")
))

(setq org-cite-global-bibliography '("~/Dropbox/references.bib"))

;; (setq! bibtex-completion-bibliography '("/path/to/references.bib"))
(setq! citar-bibliography '("~/Dropbox/references.bib"))

;; (setq! citar-library-paths '("/path/to/library/files/")
;;       citar-notes-paths '("/path/to/your/notes/"))

(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))

;; Enable vertico-multiform
(vertico-multiform-mode)

(add-to-list 'vertico-multiform-categories
             '(jinx grid (vertico-grid-annotate . 20)))
(vertico-multiform-mode 1)

(org-babel-do-load-languages
    'org-babel-load-languages
    '((d2 . t)))

(add-to-list 'exec-path "~/.local/bin/")

(require 'ox-json)

(setq org-roam-directory "~/Dropbox/roam")

(use-package! org-transclusion
              :after org
              :init
              (map!
               :map global-map "<f12>" #'org-transclusion-add
               :leader
               :prefix "n"
               :desc "Org Transclusion Mode" "t" #'org-transclusion-mode))

;; hack per risolvere il fatto che transclusion non trova i file, per qualche motivo
;; https://github.com/nobiot/org-transclusion/issues/62
(org-id-update-id-locations (directory-files org-roam-directory t "org$"))

(require 'elfeed-goodies)
(elfeed-goodies/setup)
(setq elfeed-goodies/entry-pane-size 0.5)

(require 'elfeed-score)
(elfeed-score-enable)
(define-key elfeed-search-mode-map "=" elfeed-score-map)

;; Support for React
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . typescript-mode))

;; (setq racer-rust-src-path "~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library")

(setq rustic-lsp-server 'rust-analyzer)

(after! lsp-rust
  (setq lsp-rust-server 'rust-analyzer))

(setq tokindle-epub-path "~")

(setq tokindle-epub-path-sent "~/Scaricati/epub_sent")

(setq tokindle-mobi-path-sent "~/Scaricati/mobi_sent")

(defun ebook-convert-epub-to-mobi (file)
  (format "ebook-convert \"%s\" \"%s\".mobi" file file))

(defun tokindle-calibre-smtp-cmd (filename)
  (concat "calibre-smtp "
          ;; attachment
          (format "-a \"%s.mobi\" " filename)
          ;; subject
          (format "-s \"%s\" " (file-name-nondirectory filename))
          (format "-r \"%s\" " (getenv "TOKINDLE_SMTP"))
          (format "--port \"%s\" " (getenv "TOKINDLE_PORT"))
          (format "-u \"%s\" " (getenv "TOKINDLE_USERNAME"))
          (format "-p \"%s\" " (getenv "TOKINDLE_PASSWORD"))
          (format "\"%s\" " (getenv "TOKINDLE_MY_MAIL"))
          (format "\"%s\" " (getenv "TOKINDLE_KINDLE_MAIL"))
          ;; text
          "\"\""))

(defun send-to-kindle ()
  (dolist (file (directory-files tokindle-epub-path 'full (rx ".epub" eos) 'nosort))
    (let ((filename (file-name-sans-extension file))
          (ext (file-name-extension file)))

      ;; Manage conversion between formats
      (if (not (file-exists-p (concat file ".mobi")))
          (progn
            (message (concat "Converting " file "to mobi..."))
            (shell-command (ebook-convert-epub-to-mobi file))
            (message "Converted.")))

      ;; Send the mobi files with calibre
      (if (file-exists-p (concat file ".mobi"))
          (progn
            (message (concat "Sending " (concat file ".mobi") "to your Kindle..."))
            (shell-command (tokindle-calibre-smtp-cmd file))
            (message "File sent.")))

      ;; now you can move the ebook files into the proper directories
      ;; archive the epub
      (rename-file file (file-name-concat tokindle-epub-path-sent
                                          (file-name-nondirectory file)))
      ;; archive the mobi
      (rename-file (concat file ".mobi")
                   (file-name-concat tokindle-mobi-path-sent
                                     (file-name-nondirectory (concat file ".mobi"))))
      ))
  ;; congratulations *clap clap*, the files were sent to your kindle
  (message "All available ebooks are being sent to your Kindle."))

;; try me!
;; (send-to-kindle)

;; Generate ORG/Zola frontmatter
;; TODO Section management
;; Update the directory
;; MAYBE Add hook to org file IF hugo_base_dir or hugo_section is present at top
(defun org-zola-frontmatter (slug)
  "Insert org-mode properties under a paragraph to setup ox-hugo/zola exports"
  (interactive "sEnter slug: ")
  (insert ":PROPERTIES:\n"
          (concat ":EXPORT_HUGO_SECTION: 2022/" slug "\n")
          ":EXPORT_FILE_NAME: index\n"
          ":END:\n"))

;; add "CLOSED" when an item is set with DONE state
(setq org-log-done 'time)

(setq ox-zola-special-block-type-properties '(("twitter" . (:trim-pre t :trim-post t))
                                              ("figure" . (:trim-pre t :trim-post t))))

(setq mastodon-instance-url "https://fosstodon.org"
      mastodon-active-user "gicrisf")

(defun bf-pretty-print-xml-region (begin end)
  "Pretty format XML markup in region. You need to have nxml-mode
http://www.emacswiki.org/cgi-bin/wiki/NxmlMode installed to do
this.  The function inserts linebreaks to separate tags that have
nothing but whitespace between them.  It then indents the markup
by using nxml's indentation rules."
  (interactive "r")
  (save-excursion
    (nxml-mode)
    (goto-char begin)
    (while (search-forward-regexp "\>[ \\t]*\<" nil t)
      (backward-char) (insert "\n") (setq end (1+ end)))
    (indent-region begin end)
    (normal-mode))
  (message "Ah, much better!"))

(setq which-key-idle-delay 0.5) ;; I need the help, I really do

(add-hook 'Info-selection-hook 'info-colors-fontify-node)

(setq config-org-file-name "config.org"
      config-org-directory "~/.doom.d")

(defun open-config-org ()
  "Open your private config.org file."
  (interactive)
  (find-file (expand-file-name config-org-file-name config-org-directory)))

(map! :leader
      (:prefix-map ("o" . "open")
       :desc "Open your private config.org file." "c" #'open-config-org))

(setf (nth 5 +doom-dashboard-menu-sections) '("Open org configuration" :icon (all-the-icons-octicon "tools" :face 'doom-dashboard-menu-title) :action open-config-org))

(map! :leader
      (:prefix-map ("e" . "elfeed")
       :desc "Enter elfeed." "e" #'elfeed))

(setf (nth 2 +doom-dashboard-menu-sections) '("Open elfeed" :icon (all-the-icons-octicon "rss" :face 'doom-dashboard-menu-title) :action elfeed))

(map! :leader
      (:prefix-map ("e" . "elfeed")
       :desc "Update all the feeds in elfeed." "u" #'elfeed-update))

(map! :leader
      (:prefix-map ("q" . "quit/session")
       :desc "Switch to the dashboard in the current window, of the current FRAME." "h" #'+doom-dashboard/open))

(setf (nth 3 +doom-dashboard-menu-sections) '("Open info" :icon (all-the-icons-octicon "info" :face 'doom-dashboard-menu-title) :action info))

(setf (nth 0 +doom-dashboard-menu-sections) '("Open project" :icon (all-the-icons-octicon "briefcase" :face 'doom-dashboard-menu-title) :action projectile-switch-project))

(map! :leader
      (:prefix-map ("o" . "open")
       :desc "Open org manual." "i" #'org-info))

(setf (nth 6 +doom-dashboard-menu-sections) '("Doom documentation" :icon (all-the-icons-octicon "book" :face 'doom-dashboard-menu-title) :action doom/help))

(setq wttrin-default-cities '("Caltagirone" "Bologna" "Ferrara" "Catania"))
(setq wttrin-default-accept-language '("Accept-Language" . "it-IT"))

(setq openai-key (getenv "OPENAI_KEY"))

(setq chatgpt-repo-path "~/Projects/ChatGPT.el/")

(setq gptel-api-key (getenv "OPENAI_KEY"))

(setq dall-e-n 1)
(setq dall-e-spinner-type 'flipping-line)
(setq dall-e-display-width 256)

(setq llamacs-model-path "~/ggml-alpaca-7b-q4.bin")
(setq llamacs-repo-path "~/Projects/llamacs/")

(defun +snippet--completing-read-uuid (prompt all-snippets &rest args)
  (let* ((snippet-data (cl-loop for (_ . tpl) in (mapcan #'yas--table-templates (if all-snippets
                                                                                    (hash-table-values yas--tables)
                                                                                  (yas--get-snippet-tables)))

                                for txt = (format "%-25s%-30s%s"
                                                  (yas--template-key tpl)
                                                  (yas--template-name tpl)
                                                  (abbreviate-file-name (yas--template-load-file tpl)))
                                collect
                                `(,txt . ,(yas--template-uuid tpl))))
         (selected-value (apply #'completing-read prompt snippet-data args)))
    (alist-get selected-value snippet-data nil nil 'equal)))

(defun gicrisf/emacs-lisp-byte-compile-and-load-from-path (path)
  "Byte-compile the file in PATH (if it has changed), then load compiled code."
  (interactive nil emacs-lisp-mode)
  (emacs-lisp--before-compile-buffer)
  (require 'bytecomp)
  (let ((abspath (expand-file-name path)))
    (byte-recompile-file abspath nil 0)
    (load (byte-compile-dest-file abspath))))
