#+title: Doom Emacs Configuration
#+author: Giovanni Crisalfi

The configuration lives inside a single file, the =config.org= file.
GitHub is able to render org files! If you want to read the configuration entirely, just open the file here in this repo.

> *Keep in mind* that not evey part is translated in English.

It happens to me writing stuff down in Italian, my mother language, so some sections are published as they are.
It can take some time before I translate everything in English.

If you prefer to read specific section of the configuration in a specific language, you can search for them on my blog.

[[https://www.zwitterio.it/en/tags/emacs/][Click here for english blog posts with the "EMACS" tag]]

[[https://www.zwitterio.it/tags/emacs/][Clicca qui per post in italiano sul blog con il tag "EMACS"]]

** Donate
Did you find something interesting in my dots?
Why don't you help me keeping myself awake buying me a coffee?

[[https://ko-fi.com/V7V425BFU][https://ko-fi.com/img/githubbutton_sm.svg]]

** License
Open sourced under the [[./LICENSE][MIT license]].
