#+title: Doom Emacs Configuration
#+author: Giovanni Crisalfi

The configuration lives inside a single file, [[./config.org][the =config.org= file]].
GitHub is able to render org files! If you want to read the configuration entirely, just open the file here in this repo.

#+begin_comment
*Keep in mind that not every part is translated into English*.
Since Italian is my mother language, I sometimes write sections in Italian and publish them as is. It may take some time before I can translate everything into English.
#+end_comment

In some cases, I keep Italian counterparts of my posts on my blog. If you want to read parts of the configuration in a specific language, you can find the already filtered ones at the following links.
- [[https://www.zwitterio.it/en/tags/emacs/][English (EN) blog posts with the "EMACS" tag]]
- [[https://www.zwitterio.it/tags/emacs/][Italian (IT) blog posts with the "EMACS" tag]]

** Donate
Did you find something interesting in my dots?
Why don't you help me keeping myself awake buying me a coffee?

[[https://ko-fi.com/V7V425BFU][https://ko-fi.com/img/githubbutton_sm.svg]]

** License
Open sourced under the [[./LICENSE][MIT license]].
